%{
Filename: noise_correlation_analysis_affine.m
Author: Zitong Wang
Date: 2025-03-25 (affine-shift variant)

Description:
    Characterizes noise correlation structure in pseudopopulation data from
    V1 and V2, using a deterministic affine trial-shift to break noise
    correlations instead of random shuffling.

    Affine shift construction:
      24 permutations of 10 trials generated by t -> (a*p + b) mod 10:
        Group 1 (forward shifts):  a=1, b=0..9   (10 patterns)
        Group 2 (reverse shifts):  a=9, b=0..9   (10 patterns)
        Group 3 (stride-3):        a=3, b=0..3   ( 4 patterns)
      Within each group, all pairs have 0 positional overlap.
      Across groups, worst-case overlap is 2/10 positions.

    Patterns are assigned sequentially to neurons within each recording
    session: the first neuron gets pattern 1, the second gets pattern 2,
    etc. This ensures that neurons recorded simultaneously receive distinct,
    deterministic trial reorderings.

    Stage 1: Relationship between geometric mean firing rate and noise
    correlation across stimuli per neuron pair.

    Stage 2: Mean vs variance of noise correlation across stimuli per pair.

    Affine-shift analysis: Applies the deterministic affine shift to break
    noise correlations while preserving marginal firing rate distributions.
    Produces comparison figures analogous to the random-shuffle version.

Inputs:
    - neuronal_data/<monkey>/<area>/<monkey>_<area>_allstim.mat

Outputs:
    - MAT-files: results/noise_correlation_outputs/<monkey>/<area>/
    - Figures:   results/figures/nc_affine_<monkey>_<area>/
%}

%% Initialization
clc; clear;
close all

%% Configuration
monkey     = 'KO';       % 'FR' or 'KO'
vp         = 'V2';       % 'V1' or 'V2'
timewindow = [330 630];  % spike-count window (ms)

% Affine shift configuration
run_affine_shift = true;

% NaN handling: 'zero' sets NaN NCs to 0; 'exclude' leaves them as NaN
% and uses nanmean/nanvar for downstream statistics
nan_mode = 'exclude';  % 'zero' or 'exclude'

renderings = {'ac', 'ec', 'ex'};
rendering_colors = struct('ac', [0.85 0.33 0.10], ...   % orange
                          'ec', [0.00 0.45 0.74], ...   % blue
                          'ex', [0.47 0.67 0.19]);      % green
N_renderings = numel(renderings);

%% Load data
data_file = fullfile('..','..','neuronal_data', monkey, vp, ...
    sprintf('%s_%s_allstim.mat', monkey, vp));
tmp = load(data_file, 'three_stim_array');
spike_data = tmp.three_stim_array;
clear tmp;

%% Prepare output directories — distinct from random-shuffle version
save_path_data = fullfile('..','..','results','noise_correlation_outputs', ...
    monkey, vp);
save_path_figs = fullfile('..','..','results','figures', ...
    sprintf('nc_affine_%s_%s', monkey, vp));
if ~exist(save_path_data, 'dir'), mkdir(save_path_data); end
if ~exist(save_path_figs, 'dir'), mkdir(save_path_figs); end

fig_prefix = sprintf('nc_affine_%s_%s_nan%s', monkey, vp, nan_mode);
fprintf('NaN handling mode: %s\n', nan_mode);

%% Constants
name2idx = struct('ac',1,'ec',2,'ex',3);
N_stimuli = 50;
N_trials_per_stim = 10;
rate_floor = 0.1;

%% Get neuron count and pair indices
[trial_data_tmp, ~] = multiclass_svmloader_PT(spike_data{1}, timewindow);
N_neurons = size(trial_data_tmp, 2);
N_pairs = nchoosek(N_neurons, 2);
pair_idx = nchoosek(1:N_neurons, 2);
clear trial_data_tmp;

fprintf('Monkey %s | %s | %d neurons | %d pairs\n', ...
    monkey, vp, N_neurons, N_pairs);

%% Determine session membership for each neuron
% Read session files from the 'ac' folder (bad_channels are the same across renderings)
session_dir = fullfile('..','..','neuronal_data', monkey, vp, 'ac');
all_files = dir(fullfile(session_dir, '*.mat'));

% Filter out the combined population file (e.g., FR_V1_ac.mat)
combined_pattern = sprintf('%s_%s_ac.mat', monkey, vp);
session_files = {};
for f = 1:numel(all_files)
    if ~strcmpi(all_files(f).name, combined_pattern)
        session_files{end+1} = all_files(f).name;
    end
end
session_files = sort(session_files); % chronological order by filename
N_sessions = numel(session_files);

% Build neuron-to-session mapping
neuron_session_id = []; % session index for each neuron in the population
neurons_per_session = zeros(N_sessions, 1);
for sess = 1:N_sessions
    sess_data = load(fullfile(session_dir, session_files{sess}), 'bad_channel');
    good_channels = setdiff(1:24, sess_data.bad_channel);
    n_good = numel(good_channels);
    neuron_session_id = [neuron_session_id; repmat(sess, n_good, 1)];
    neurons_per_session(sess) = n_good;
    fprintf('  Session %d (%s): %d good channels\n', sess, session_files{sess}, n_good);
end

% Verify neuron count matches
assert(numel(neuron_session_id) == N_neurons, ...
    'Session neuron count (%d) does not match population size (%d)', ...
    numel(neuron_session_id), N_neurons);
fprintf('Session mapping: %d sessions, %d total neurons\n', N_sessions, sum(neurons_per_session));

% Classify each pair as same-session or cross-session
is_same_session = (neuron_session_id(pair_idx(:,1)) == neuron_session_id(pair_idx(:,2)));
N_same    = sum(is_same_session);
N_cross   = sum(~is_same_session);
fprintf('Pairs: %d same-session, %d cross-session\n', N_same, N_cross);

%% ==================== AFFINE SHIFT PATTERNS ====================
% Generate 24 deterministic trial permutations via t -> (a*p + b) mod 10
% Positions and trials are 0-indexed internally, then converted to 1-indexed.

affine_patterns = zeros(24, N_trials_per_stim);
pattern_count = 0;

% Group 1: Forward shifts (a = 1, b = 0..9)
for b = 0:9
    pattern_count = pattern_count + 1;
    for p = 0:(N_trials_per_stim - 1)
        affine_patterns(pattern_count, p+1) = mod(1*p + b, 10) + 1;
    end
end

% Group 2: Reverse shifts (a = 9, b = 0..9)
for b = 0:9
    pattern_count = pattern_count + 1;
    for p = 0:(N_trials_per_stim - 1)
        affine_patterns(pattern_count, p+1) = mod(9*p + b, 10) + 1;
    end
end

% Group 3: Stride-3 (a = 3, b = 0..3)
for b = 0:3
    pattern_count = pattern_count + 1;
    for p = 0:(N_trials_per_stim - 1)
        affine_patterns(pattern_count, p+1) = mod(3*p + b, 10) + 1;
    end
end

assert(pattern_count == 24, 'Expected 24 affine patterns, got %d', pattern_count);

% Print patterns for verification
fprintf('\n--- Affine shift patterns ---\n');
group_names = [repmat({'Fwd'}, 1, 10), repmat({'Rev'}, 1, 10), repmat({'Str3'}, 1, 4)];
for k = 1:24
    fprintf('  Pattern %2d (%s): [%s]\n', k, group_names{k}, ...
        strjoin(arrayfun(@num2str, affine_patterns(k,:), 'UniformOutput', false), ', '));
end

%% Assign affine pattern to each neuron based on session membership
% Within each session, neurons are assigned patterns 1, 2, 3, ... sequentially.
neuron_pattern_id = zeros(N_neurons, 1);
for sess = 1:N_sessions
    sess_neuron_indices = find(neuron_session_id == sess);
    n_in_sess = numel(sess_neuron_indices);
    assert(n_in_sess <= 24, ...
        'Session %d has %d neurons, exceeding 24 available patterns', sess, n_in_sess);
    for k = 1:n_in_sess
        neuron_pattern_id(sess_neuron_indices(k)) = k;
    end
    fprintf('Session %d: %d neurons -> patterns 1-%d assigned\n', sess, n_in_sess, n_in_sess);
end

% Summary: how many neurons use each pattern group
n_fwd  = sum(neuron_pattern_id <= 10);
n_rev  = sum(neuron_pattern_id > 10 & neuron_pattern_id <= 20);
n_str3 = sum(neuron_pattern_id > 20);
fprintf('Pattern usage: %d forward, %d reverse, %d stride-3\n', n_fwd, n_rev, n_str3);

%% Select 40 example pairs (shared across renderings)
n_examples = 40;
rng(42);
example_pair_indices = randsample(N_pairs, n_examples);

%% Preallocate storage
all_results = struct();

%% ===== MAIN LOOP: Process each rendering =====
for r = 1:N_renderings
    rend = renderings{r};
    rendering_idx = name2idx.(rend);
    fprintf('\n========== Processing %s ==========\n', upper(rend));

    % Load and format trial data
    [trial_data, labels] = multiclass_svmloader_PT(spike_data{rendering_idx}, timewindow);

    % Reorganize: [N_stimuli x N_trials_per_stim x N_neurons]
    data_by_stim = zeros(N_stimuli, N_trials_per_stim, N_neurons);
    for s = 1:N_stimuli
        data_by_stim(s, :, :) = trial_data(labels == s, :);
    end

    % Mean firing rate per stimulus per neuron: [N_stimuli x N_neurons]
    mean_rates = squeeze(mean(data_by_stim, 2));
    mean_rates_floored = max(mean_rates, rate_floor);

    % ---- Original data: compute NC and geo mean ----
    [nc_per_stim, geomean_per_stim] = compute_nc_geomean( ...
        data_by_stim, mean_rates_floored, pair_idx, N_pairs, N_stimuli, nan_mode);

    % Per-pair correlation between geo mean and NC
    geomean_nc_corr = compute_geomean_nc_corr(geomean_per_stim, nc_per_stim, N_pairs);

    % Mean and variance of NC across stimuli (NaN-aware)
    mean_nc = mean(nc_per_stim, 2, 'omitnan');
    var_nc  = var(nc_per_stim, 0, 2, 'omitnan');

    % Store original results
    all_results.(rend).nc_per_stim      = nc_per_stim;
    all_results.(rend).geomean_per_stim = geomean_per_stim;
    all_results.(rend).geomean_nc_corr  = geomean_nc_corr;
    all_results.(rend).mean_nc          = mean_nc;
    all_results.(rend).var_nc           = var_nc;

    % ---- Affine shift analysis ----
    if run_affine_shift
        fprintf('Applying affine trial shift for %s...\n', upper(rend));

        % Apply deterministic affine shift: each neuron's trials are
        % reordered according to its assigned pattern, identically for
        % every stimulus.
        data_by_stim_shifted = zeros(size(data_by_stim));
        for n = 1:N_neurons
            pat = affine_patterns(neuron_pattern_id(n), :);
            for s = 1:N_stimuli
                data_by_stim_shifted(s, :, n) = data_by_stim(s, pat, n);
            end
        end

        % Compute NC on shifted data (geo means unchanged)
        [nc_shifted, ~] = compute_nc_geomean( ...
            data_by_stim_shifted, mean_rates_floored, pair_idx, N_pairs, N_stimuli, nan_mode);

        % Per-pair geo-mean-NC correlation on shifted data
        shifted_geomean_nc_corr = compute_geomean_nc_corr( ...
            geomean_per_stim, nc_shifted, N_pairs);

        % Mean and variance of NC across stimuli (shifted)
        shifted_mean_nc = mean(nc_shifted, 2, 'omitnan');
        shifted_var_nc  = var(nc_shifted, 0, 2, 'omitnan');

        % Store shifted results
        all_results.(rend).shifted_nc_per_stim      = nc_shifted;
        all_results.(rend).shifted_geomean_nc_corr  = shifted_geomean_nc_corr;
        all_results.(rend).shifted_mean_nc           = shifted_mean_nc;
        all_results.(rend).shifted_var_nc            = shifted_var_nc;

        % Population-level summary statistics (for comparison)
        all_results.(rend).real_pop_mean_nc              = mean(mean_nc, 'omitnan');
        all_results.(rend).shifted_pop_mean_nc           = mean(shifted_mean_nc, 'omitnan');
        all_results.(rend).real_pop_median_geomean_nc    = median(geomean_nc_corr, 'omitnan');
        all_results.(rend).shifted_pop_median_geomean_nc = median(shifted_geomean_nc_corr, 'omitnan');

        fprintf('Affine shift analysis complete for %s.\n', upper(rend));
    end
end

%% ==================== ORIGINAL FIGURES ====================

% NaN-safe summary functions for annotations
nmean   = @(x) mean(x, 'omitnan');
nmedian = @(x) median(x, 'omitnan');

%% Determine shared x-axis range for example scatter plots
all_geomeans = [];
for r = 1:N_renderings
    rend = renderings{r};
    all_geomeans = [all_geomeans; ...
        all_results.(rend).geomean_per_stim(example_pair_indices, :)];
end
shared_x_max = ceil(max(all_geomeans(:)));
shared_xlim_examples = [0 shared_x_max];
shared_ylim_examples = [-1 1];

%% FIGURE 1-3: Stage 1 Example Scatter Plots (one per rendering)
n_cols = 8;
n_rows = ceil(n_examples / n_cols);

for r = 1:N_renderings
    rend = renderings{r};
    clr = rendering_colors.(rend);

    fig = figure('Position', [50 50 2000 n_rows * 200]);
    for k = 1:n_examples
        p = example_pair_indices(k);
        ni = pair_idx(p, 1);
        nj = pair_idx(p, 2);

        subplot(n_rows, n_cols, k);
        scatter(all_results.(rend).geomean_per_stim(p, :), ...
                all_results.(rend).nc_per_stim(p, :), ...
                15, clr, 'filled', 'MarkerFaceAlpha', 0.6);
        hold on;
        coeffs = polyfit(all_results.(rend).geomean_per_stim(p, :), ...
                         all_results.(rend).nc_per_stim(p, :), 1);
        x_line = linspace(shared_xlim_examples(1), shared_xlim_examples(2), 100);
        plot(x_line, polyval(coeffs, x_line), 'r-', 'LineWidth', 1);
        yline(0, 'k:', 'LineWidth', 0.5);
        hold off;

        xlim(shared_xlim_examples);
        ylim(shared_ylim_examples);

        title(sprintf('(%d,%d) r=%.2f', ni, nj, ...
            all_results.(rend).geomean_nc_corr(p)), 'FontSize', 7);
        if k > (n_rows - 1) * n_cols
            xlabel('Geo mean', 'FontSize', 7);
        end
        if mod(k - 1, n_cols) == 0
            ylabel('NC', 'FontSize', 7);
        end
        set(gca, 'FontSize', 6);
    end
    sgtitle(sprintf('%s %s %s — Geo Mean vs Noise Correlation (40 example pairs)', ...
        monkey, vp, upper(rend)), 'FontSize', 12);
    % saveas(fig, fullfile(save_path_figs, ...
    %     sprintf('%s_%s_stage1_example_scatter.png', fig_prefix, rend)));
end

%% FIGURE 4: Stage 1 Distribution of Geo Mean-NC Correlations (3 renderings)
fig4 = figure('Position', [100 100 900 600]);
hold on;
legend_entries = cell(1, N_renderings);
for r = 1:N_renderings
    rend = renderings{r};
    clr = rendering_colors.(rend);
    histogram(all_results.(rend).geomean_nc_corr, 50, ...
        'FaceColor', clr, 'EdgeColor', 'w', 'FaceAlpha', 0.5);
    legend_entries{r} = sprintf('%s (med=%.3f)', upper(rend), ...
        nmedian(all_results.(rend).geomean_nc_corr));
end
xline(0, 'k--', 'LineWidth', 1);
hold off;
xlabel('Correlation (geo mean vs NC)');
ylabel('Number of neuron pairs');
title(sprintf('%s %s — Distribution of Geo Mean-NC Correlations', monkey, vp));
legend(legend_entries, 'Location', 'best');
% saveas(fig4, fullfile(save_path_figs, ...
%     sprintf('%s_stage1_geomean_nc_corr_distribution.png', fig_prefix)));

%% FIGURE 5a-c version1: Stage 2 Scatterhist (one per rendering)
all_mean_nc_cat = [];
all_var_nc_cat  = [];
for r = 1:N_renderings
    rend = renderings{r};
    all_mean_nc_cat = [all_mean_nc_cat; all_results.(rend).mean_nc];
    all_var_nc_cat  = [all_var_nc_cat;  all_results.(rend).var_nc];
end
shared_xlim_s2 = [floor(min(all_mean_nc_cat)*20)/20, ceil(max(all_mean_nc_cat)*20)/20];
shared_ylim_s2 = [floor(min(all_var_nc_cat)*100)/100, ceil(max(all_var_nc_cat)*100)/100];

for r = 1:N_renderings
    rend = renderings{r};
    clr = rendering_colors.(rend);
    mn = all_results.(rend).mean_nc;
    vn = all_results.(rend).var_nc;

    fig5 = figure('Position', [50 + (r-1)*500, 100, 800, 800]);
    h = scatterhist(mn, vn, ...
        'Direction', 'out', 'Color', clr, 'Marker', '.', 'MarkerSize', 8);

    xlim(h(1), shared_xlim_s2);
    ylim(h(1), shared_ylim_s2);

    % Regression line
    hold(h(1), 'on');
    valid = ~isnan(mn) & ~isnan(vn);
    coeffs = polyfit(mn(valid), vn(valid), 1);
    x_line = linspace(shared_xlim_s2(1), shared_xlim_s2(2), 100);
    plot(h(1), x_line, polyval(coeffs, x_line), 'r-', 'LineWidth', 1.5);
    R2 = corrcoef(mn(valid), vn(valid));
    text(h(1), 0.05, 0.95, sprintf('r = %.3f', R2(1,2)), ...
        'Units', 'normalized', 'FontSize', 11, 'VerticalAlignment', 'top');
    hold(h(1), 'off');

    % Marginal annotations: mean (red) and median (black)
    hold(h(2), 'on');
    y_top = ylim(h(2));
    plot(h(2), [nmean(mn) nmean(mn)], y_top, 'r-', 'LineWidth', 1.5);
    plot(h(2), [nmedian(mn) nmedian(mn)], y_top, 'k--', 'LineWidth', 1.5);
    text(h(2), 0.02, 0.95, sprintf('mean: %.3f', nmean(mn)), ...
        'Units', 'normalized', 'FontSize', 10, 'Color', 'r', 'VerticalAlignment', 'top');
    text(h(2), 0.02, 0.75, sprintf('median: %.3f', nmedian(mn)), ...
        'Units', 'normalized', 'FontSize', 10, 'Color', 'k', 'VerticalAlignment', 'top');
    hold(h(2), 'off');

    hold(h(3), 'on');
    y_right = ylim(h(3));
    plot(h(3), [nmean(vn) nmean(vn)], y_right, 'r-', 'LineWidth', 1.5);
    plot(h(3), [nmedian(vn) nmedian(vn)], y_right, 'k--', 'LineWidth', 1.5);
    text(h(3), 0.02, 0.95, sprintf('mean: %.4f', nmean(vn)), ...
        'Units', 'normalized', 'FontSize', 10, 'Color', 'r', 'VerticalAlignment', 'top');
    text(h(3), 0.02, 0.75, sprintf('median: %.4f', nmedian(vn)), ...
        'Units', 'normalized', 'FontSize', 10, 'Color', 'k', 'VerticalAlignment', 'top');
    hold(h(3), 'off');

    xlabel(h(1), 'Mean noise correlation');
    ylabel(h(1), 'Variance of noise correlation');
    title(h(1), sprintf('%s %s %s — Mean vs Variance of NC (%d pairs)', ...
        monkey, vp, upper(rend), N_pairs));

    % saveas(fig5, fullfile(save_path_figs, ...
    %     sprintf('%s_%s_stage2_mean_vs_variance_nc.png', fig_prefix, rend)));
end

%% FIGURE 5a-c version2: Stage 2 Scatterhist by session type (one per rendering)
all_mean_nc_cat = [];
all_var_nc_cat  = [];
for r = 1:N_renderings
    rend = renderings{r};
    all_mean_nc_cat = [all_mean_nc_cat; all_results.(rend).mean_nc];
    all_var_nc_cat  = [all_var_nc_cat;  all_results.(rend).var_nc];
end
shared_xlim_s2 = [floor(min(all_mean_nc_cat)*20)/20, ceil(max(all_mean_nc_cat)*20)/20];
shared_ylim_s2 = [floor(min(all_var_nc_cat)*100)/100, ceil(max(all_var_nc_cat)*100)/100];

% Session group labels for pairs
pair_session_labels = cell(N_pairs, 1);
pair_session_labels(is_same_session)  = {'Same session'};
pair_session_labels(~is_same_session) = {'Cross session'};

% Colors: same-session = rendering color, cross-session = purple
session_color_cross = [0.55 0.25 0.65];  % purple

for r = 1:N_renderings
    rend = renderings{r};
    clr = rendering_colors.(rend);
    mn = all_results.(rend).mean_nc;
    vn = all_results.(rend).var_nc;

    fig5 = figure('Position', [50 + (r-1)*500, 100, 800, 800]);

    % Order: cross-session first (background), same-session on top
    reorder = [find(~is_same_session); find(is_same_session)];
    mn_ordered = mn(reorder);
    vn_ordered = vn(reorder);
    labels_ordered = pair_session_labels(reorder);

    h = scatterhist(mn_ordered, vn_ordered, 'Group', labels_ordered, ...
        'Color', [session_color_cross; clr], ...
        'Marker', '..', ...
        'MarkerSize', [6 8], ...
        'Kernel', 'on', ...
        'Direction', 'out');

    xlim(h(1), shared_xlim_s2);
    ylim(h(1), shared_ylim_s2);

    % Marginal annotations
    hold(h(2), 'on');
    text(h(2), 0.8, 0.95, sprintf('Same mean: %.3f', nmean(mn(is_same_session))), ...
        'Units', 'normalized', 'FontSize', 10, 'Color', clr, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(h(2), 0.8, 0.80, sprintf('Cross mean: %.3f', nmean(mn(~is_same_session))), ...
        'Units', 'normalized', 'FontSize', 10, 'Color', session_color_cross, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    hold(h(2), 'off');

    hold(h(3), 'on');
    text(h(3), 0.02, 0.95, sprintf('Same mean: %.4f', nmean(vn(is_same_session))), ...
        'Units', 'normalized', 'FontSize', 10, 'Color', clr, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(h(3), 0.02, 0.90, sprintf('Cross mean: %.4f', nmean(vn(~is_same_session))), ...
        'Units', 'normalized', 'FontSize', 10, 'Color', session_color_cross, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    hold(h(3), 'off');

    xlabel(h(1), 'Mean noise correlation');
    ylabel(h(1), 'Variance of noise correlation');
    title(h(1), sprintf('%s %s %s — Mean vs Var NC (%d same, %d cross)', ...
        monkey, vp, upper(rend), N_same, N_cross));
    legend(h(1), 'Location', 'best');

    % saveas(fig5, fullfile(save_path_figs, ...
    %     sprintf('%s_%s_stage2_mean_vs_variance_nc_session.png', fig_prefix, rend)));
end

%% ==================== AFFINE SHIFT FIGURES ====================
if run_affine_shift

%% FIGURE 6: Stage 1 Geo Mean-NC Correlation: Original vs Affine-Shifted (3 subplots)
fig6 = figure('Position', [100 100 2500 500]);
for r = 1:N_renderings
    rend = renderings{r};
    clr = rendering_colors.(rend);

    orig_vals    = all_results.(rend).geomean_nc_corr;
    shifted_vals = all_results.(rend).shifted_geomean_nc_corr;

    subplot(1, 3, r);
    hold on;
    % Affine-shifted distribution (black)
    histogram(shifted_vals, 50, ...
        'FaceColor', [0 0 0], 'EdgeColor', 'w', 'FaceAlpha', 1);
    % Original distribution (colored)
    histogram(orig_vals, 50, ...
        'FaceColor', clr, 'EdgeColor', 'w', 'FaceAlpha', 0.5);

    xline(0, 'k:', 'LineWidth', 0.5);
    hold off;

    xlabel('Correlation (geo mean vs NC)');
    ylabel('Number of neuron pairs');
    title(sprintf('%s', upper(rend)));

    % Text annotations
    text(0.02, 0.95, sprintf('Original mean: %.3f', nmean(orig_vals)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', clr, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(0.02, 0.87, sprintf('Original median: %.3f', nmedian(orig_vals)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', clr, ...
        'VerticalAlignment', 'top');
    text(0.02, 0.79, sprintf('Shifted mean: %.3f', nmean(shifted_vals)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', [0.3 0.3 0.3], ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(0.02, 0.71, sprintf('Shifted median: %.3f', nmedian(shifted_vals)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', [0.3 0.3 0.3], ...
        'VerticalAlignment', 'top');

    legend('Affine-shifted', 'Original', 'Location', 'northeast');
end
sgtitle(sprintf('%s %s — Geo Mean-NC Correlation: Original vs Affine Shift', ...
    monkey, vp), 'FontSize', 12);
% saveas(fig6, fullfile(save_path_figs, ...
%     sprintf('%s_stage1_geomean_nc_corr_original_vs_affine.png', fig_prefix)));

%% FIGURE 7a-c version1: Stage 2 Scatterhist Original vs Affine-Shifted (one per rendering)
for r = 1:N_renderings
    rend = renderings{r};
    clr = rendering_colors.(rend);

    % Original data
    mn_orig = all_results.(rend).mean_nc;
    vn_orig = all_results.(rend).var_nc;

    % Affine-shifted data
    mn_shifted = all_results.(rend).shifted_mean_nc;
    vn_shifted = all_results.(rend).shifted_var_nc;

    % Concatenate: shifted first so original plots on top
    all_mn = [mn_shifted; mn_orig];
    all_vn = [vn_shifted; vn_orig];
    group_labels = [repmat({'Affine-shifted'}, length(mn_shifted), 1); ...
                    repmat({'Original'}, length(mn_orig), 1)];

    fig7 = figure('Position', [50 + (r-1)*500, 100, 800, 800]);
    h = scatterhist(all_mn, all_vn, 'Group', group_labels, ...
        'Color', [0.7 0.7 0.7; clr], ...
        'Marker', '..', ...
        'MarkerSize', [4 8], ...
        'Kernel', 'on', ...
        'Direction', 'out');

    xlim(h(1), shared_xlim_s2);
    ylim(h(1), shared_ylim_s2);

    % Annotate top marginal (mean NC distribution)
    text(h(2), 0.02, 0.95, sprintf('Orig mean: %.3f', nmean(mn_orig)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', clr, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(h(2), 0.02, 0.80, sprintf('Orig median: %.3f', nmedian(mn_orig)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', clr, ...
        'VerticalAlignment', 'top');
    text(h(2), 0.02, 0.65, sprintf('Shift mean: %.3f', nmean(mn_shifted)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', [0.4 0.4 0.4], ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(h(2), 0.02, 0.50, sprintf('Shift median: %.3f', nmedian(mn_shifted)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', [0.4 0.4 0.4], ...
        'VerticalAlignment', 'top');

    % Annotate right marginal (variance of NC distribution)
    text(h(3), 0.02, 0.95, sprintf('Orig mean: %.4f', nmean(vn_orig)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', clr, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(h(3), 0.02, 0.80, sprintf('Orig median: %.4f', nmedian(vn_orig)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', clr, ...
        'VerticalAlignment', 'top');
    text(h(3), 0.02, 0.65, sprintf('Shift mean: %.4f', nmean(vn_shifted)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', [0.4 0.4 0.4], ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(h(3), 0.02, 0.50, sprintf('Shift median: %.4f', nmedian(vn_shifted)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', [0.4 0.4 0.4], ...
        'VerticalAlignment', 'top');

    xlabel(h(1), 'Mean noise correlation');
    ylabel(h(1), 'Variance of noise correlation');
    title(h(1), sprintf('%s %s %s — Original vs Affine Shift (%d pairs)', ...
        monkey, vp, upper(rend), N_pairs));
    legend(h(1), 'Location', 'best');

    % saveas(fig7, fullfile(save_path_figs, ...
    %     sprintf('%s_%s_stage2_mean_vs_variance_nc_vs_affine.png', fig_prefix, rend)));
end

%% FIGURE 7a-c version2: Stage 2 Scatterhist Original vs Affine-Shifted by session (one per rendering)
for r = 1:N_renderings
    rend = renderings{r};
    clr = rendering_colors.(rend);

    % Original data split by session
    mn_orig = all_results.(rend).mean_nc;
    vn_orig = all_results.(rend).var_nc;

    mn_orig_same  = mn_orig(is_same_session);
    vn_orig_same  = vn_orig(is_same_session);
    mn_orig_cross = mn_orig(~is_same_session);
    vn_orig_cross = vn_orig(~is_same_session);

    % Affine-shifted data split by session
    mn_shifted = all_results.(rend).shifted_mean_nc;
    vn_shifted = all_results.(rend).shifted_var_nc;

    mn_shifted_same  = mn_shifted(is_same_session);
    vn_shifted_same  = vn_shifted(is_same_session);
    mn_shifted_cross = mn_shifted(~is_same_session);
    vn_shifted_cross = vn_shifted(~is_same_session);

    % Concatenate: shifted first (background), originals on top; cross before same
    all_mn = [mn_shifted_cross; mn_shifted_same; mn_orig_cross; mn_orig_same];
    all_vn = [vn_shifted_cross; vn_shifted_same; vn_orig_cross; vn_orig_same];
    group_labels = [repmat({'Shift cross'}, length(mn_shifted_cross), 1); ...
                    repmat({'Shift same'},  length(mn_shifted_same), 1); ...
                    repmat({'Orig cross'},  length(mn_orig_cross), 1); ...
                    repmat({'Orig same'},   length(mn_orig_same), 1)];

    % Colors: gray=shift cross, black=shift same, purple=orig cross, rendering=orig same
    color_4group = [0.7 0.7 0.7; ...      % Shift cross - gray
                    0.0 0.0 0.0; ...       % Shift same  - black
                    session_color_cross; ... % Orig cross  - purple
                    clr];                   % Orig same   - rendering color

    fig7v2 = figure('Position', [50 + (r-1)*500, 100, 1000, 1000]);
    h = scatterhist(all_mn, all_vn, 'Group', group_labels, ...
        'Color', color_4group, ...
        'Marker', '....', ...
        'MarkerSize', [3 4 6 8], ...
        'Kernel', 'on', ...
        'Direction', 'out');

    xlim(h(1), shared_xlim_s2);
    ylim(h(1), shared_ylim_s2);

    % Annotate top marginal
    text(h(2), 0.8, 0.95, sprintf('Orig same: %.3f', nmean(mn_orig_same)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', clr, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(h(2), 0.8, 0.82, sprintf('Orig cross: %.3f', nmean(mn_orig_cross)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', session_color_cross, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(h(2), 0.8, 0.69, sprintf('Shift same: %.3f', nmean(mn_shifted_same)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', [0 0 0], ...
        'VerticalAlignment', 'top');
    text(h(2), 0.8, 0.56, sprintf('Shift cross: %.3f', nmean(mn_shifted_cross)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', [0.4 0.4 0.4], ...
        'VerticalAlignment', 'top');

    % Annotate right marginal
    text(h(3), 0.02, 0.95, sprintf('Orig same: %.4f', nmean(vn_orig_same)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', clr, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(h(3), 0.02, 0.90, sprintf('Orig cross: %.4f', nmean(vn_orig_cross)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', session_color_cross, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(h(3), 0.02, 0.85, sprintf('Shift same: %.4f', nmean(vn_shifted_same)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', [0 0 0], ...
        'VerticalAlignment', 'top');
    text(h(3), 0.02, 0.80, sprintf('Shift cross: %.4f', nmean(vn_shifted_cross)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', [0.4 0.4 0.4], ...
        'VerticalAlignment', 'top');

    xlabel(h(1), 'Mean noise correlation');
    ylabel(h(1), 'Variance of noise correlation');
    title(h(1), sprintf('%s %s %s — Orig vs Affine Shift by session (%d same, %d cross)', ...
        monkey, vp, upper(rend), N_same, N_cross));
    legend(h(1), 'Location', 'best');

    saveas(fig7v2, fullfile(save_path_figs, ...
        sprintf('%s_%s_stage2_mean_vs_variance_nc_vs_affine_session.png', fig_prefix, rend)));
end

%% FIGURE 8: Summary Comparison — Original vs Affine-Shifted (bar chart)
fig8 = figure('Position', [100 100 1800 700]);

for r = 1:N_renderings
    rend = renderings{r};
    clr = rendering_colors.(rend);

    % --- Top row: Population mean NC ---
    subplot(2, 3, r);
    bar_vals = [all_results.(rend).real_pop_mean_nc, ...
                all_results.(rend).shifted_pop_mean_nc];
    b = bar(bar_vals, 0.6);
    b.FaceColor = 'flat';
    b.CData(1,:) = clr;
    b.CData(2,:) = [0.4 0.4 0.4];
    set(gca, 'XTickLabel', {'Original', 'Affine-shifted'}, 'FontSize', 9);
    ylabel('Population mean NC');
    title(sprintf('%s — Pop. mean NC', upper(rend)));
    text(1, bar_vals(1)*1.1, sprintf('%.4f', bar_vals(1)), ...
        'HorizontalAlignment', 'center', 'FontSize', 9, 'Color', clr);
    text(2, bar_vals(2)*1.1, sprintf('%.4f', bar_vals(2)), ...
        'HorizontalAlignment', 'center', 'FontSize', 9, 'Color', [0.3 0.3 0.3]);

    % --- Bottom row: Median geo-mean-NC correlation ---
    subplot(2, 3, r + 3);
    bar_vals = [all_results.(rend).real_pop_median_geomean_nc, ...
                all_results.(rend).shifted_pop_median_geomean_nc];
    b = bar(bar_vals, 0.6);
    b.FaceColor = 'flat';
    b.CData(1,:) = clr;
    b.CData(2,:) = [0.6 0.6 0.6];
    set(gca, 'XTickLabel', {'Original', 'Affine-shifted'}, 'FontSize', 9);
    ylabel('Median geo-mean-NC corr.');
    title(sprintf('%s — Med. geo-NC corr.', upper(rend)));
    text(1, bar_vals(1)*1.1, sprintf('%.4f', bar_vals(1)), ...
        'HorizontalAlignment', 'center', 'FontSize', 9, 'Color', clr);
    text(2, bar_vals(2)*1.1, sprintf('%.4f', bar_vals(2)), ...
        'HorizontalAlignment', 'center', 'FontSize', 9, 'Color', [0.4 0.4 0.4]);
end

sgtitle(sprintf('%s %s — Original vs Affine Shift: Summary', ...
    monkey, vp), 'FontSize', 12);
% saveas(fig8, fullfile(save_path_figs, ...
%     sprintf('%s_summary_original_vs_affine.png', fig_prefix)));

%% FIGURE 9: Delta Mean NC (Original - Affine-Shifted) by session type (3 subplots)
fig9 = figure('Position', [100 100 2500 500]);
for r = 1:N_renderings
    rend = renderings{r};
    clr = rendering_colors.(rend);

    % Delta: original mean NC minus affine-shifted mean NC [N_pairs x 1]
    delta_nc = all_results.(rend).mean_nc - all_results.(rend).shifted_mean_nc;

    % Split by session type
    delta_same  = delta_nc(is_same_session);
    delta_cross = delta_nc(~is_same_session);

    % Remove NaN
    delta_same  = delta_same(~isnan(delta_same));
    delta_cross = delta_cross(~isnan(delta_cross));

    subplot(1, 3, r);
    hold on;
    histogram(delta_cross, 80, ...
        'FaceColor', session_color_cross, 'EdgeColor', 'w', 'FaceAlpha', 0.6, ...
        'Normalization', 'probability');
    histogram(delta_same, 80, ...
        'FaceColor', clr, 'EdgeColor', 'w', 'FaceAlpha', 0.6, ...
        'Normalization', 'probability');
    xline(0, 'k:', 'LineWidth', 1);
    xline(nmean(delta_same), '-', 'Color', clr, 'LineWidth', 1.5);
    xline(nmean(delta_cross), '-', 'Color', session_color_cross, 'LineWidth', 1.5);
    hold off;

    xlabel('\Delta Mean NC (original - affine-shifted)');
    ylabel('Probability');
    title(sprintf('%s', upper(rend)));

    text(0.02, 0.95, sprintf('Same mean \\Delta: %.4f', nmean(delta_same)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', clr, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(0.02, 0.87, sprintf('Same median \\Delta: %.4f', nmedian(delta_same)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', clr, ...
        'VerticalAlignment', 'top');
    text(0.02, 0.79, sprintf('Cross mean \\Delta: %.4f', nmean(delta_cross)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', session_color_cross, ...
        'VerticalAlignment', 'top', 'FontWeight', 'bold');
    text(0.02, 0.71, sprintf('Cross median \\Delta: %.4f', nmedian(delta_cross)), ...
        'Units', 'normalized', 'FontSize', 9, 'Color', session_color_cross, ...
        'VerticalAlignment', 'top');

    legend('Cross session', 'Same session', 'Location', 'northeast');
end
sgtitle(sprintf('%s %s — \\Delta Mean NC (Original - Affine Shift) by session', ...
    monkey, vp), 'FontSize', 12);
saveas(fig9, fullfile(save_path_figs, ...
    sprintf('%s_delta_mean_nc_by_session.png', fig_prefix)));

end % end affine shift figures

%% Save all results
% results = struct();
% results.monkey     = monkey;
% results.vp         = vp;
% results.timewindow = timewindow;
% results.pair_idx   = pair_idx;
% results.example_pair_indices = example_pair_indices;
% results.affine_patterns      = affine_patterns;
% results.neuron_pattern_id    = neuron_pattern_id;
% results.renderings = all_results;
%
% save(fullfile(save_path_data, 'noise_correlation_results_affine.mat'), 'results', '-v7.3');
% fprintf('\nAll results saved to %s\n', save_path_data);

%% ==================== HELPER FUNCTIONS ====================

function [nc_per_stim, geomean_per_stim] = compute_nc_geomean( ...
    data_by_stim, mean_rates_floored, pair_idx, N_pairs, N_stimuli, nan_mode)
% Compute pairwise noise correlation and geometric mean for all pairs and stimuli

    nc_per_stim      = zeros(N_pairs, N_stimuli);
    geomean_per_stim = zeros(N_pairs, N_stimuli);

    for p = 1:N_pairs
        ni = pair_idx(p, 1);
        nj = pair_idx(p, 2);
        for s = 1:N_stimuli
            ri = data_by_stim(s, :, ni)';
            rj = data_by_stim(s, :, nj)';
            R = corrcoef(ri, rj);
            nc_per_stim(p, s) = R(1, 2);
            geomean_per_stim(p, s) = sqrt(mean_rates_floored(s, ni) * mean_rates_floored(s, nj));
        end
    end

    % Handle NaN
    nan_count = sum(isnan(nc_per_stim(:)));
    if nan_count > 0
        fprintf('  Warning: %d NaN noise correlations.', nan_count);
        if strcmp(nan_mode, 'zero')
            fprintf(' Setting to 0.\n');
            nc_per_stim(isnan(nc_per_stim)) = 0;
        else
            fprintf(' Excluding from statistics.\n');
        end
    end
end

function geomean_nc_corr = compute_geomean_nc_corr(geomean_per_stim, nc_per_stim, N_pairs)
% Compute per-pair correlation between geometric mean and noise correlation
% Handles NaN by using only non-NaN stimulus entries per pair
    geomean_nc_corr = zeros(N_pairs, 1);
    for p = 1:N_pairs
        valid = ~isnan(nc_per_stim(p, :));
        if sum(valid) < 3
            geomean_nc_corr(p) = NaN;
        else
            R = corrcoef(geomean_per_stim(p, valid), nc_per_stim(p, valid));
            geomean_nc_corr(p) = R(1, 2);
        end
    end
    geomean_nc_corr(isnan(geomean_nc_corr)) = 0;
end
